Kronos-Shifts-Connector/Microsoft.Teams.Shifts.Integration/Microsoft.Teams.Shifts.Integration.Configuration/Controllers/TeamDepartmentMappingController.cs
// <copyright file="TeamDepartmentMappingController.cs" company="Microsoft">
// Copyright (c) Microsoft. All rights reserved.
// </copyright>

namespace Microsoft.Teams.Shifts.Integration.Configuration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Reflection;
    using System.Threading.Tasks;
    using ClosedXML.Excel;
    using Microsoft.ApplicationInsights;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Distributed;
    using Microsoft.Graph;
    using Microsoft.Teams.App.KronosWfc.BusinessLogic.HyperFindLoadAll;
    using Microsoft.Teams.App.KronosWfc.BusinessLogic.Logon;
    using Microsoft.Teams.Shifts.Integration.API.Common;
    using Microsoft.Teams.Shifts.Integration.BusinessLogic.Models;
    using Microsoft.Teams.Shifts.Integration.BusinessLogic.Providers;
    using Microsoft.Teams.Shifts.Integration.Configuration.Extensions;
    using Microsoft.Teams.Shifts.Integration.Configuration.Extensions.Alerts;
    using Microsoft.Teams.Shifts.Integration.Configuration.Helper;
    using Microsoft.Teams.Shifts.Integration.Configuration.Models;
    using Newtonsoft.Json;

    /// <summary>
    /// The Shifts team to Kronos department mapping controller.
    /// </summary>
    [Authorize]
    public class TeamDepartmentMappingController : Controller
    {
        private readonly ITeamDepartmentMappingProvider teamDepartmentMappingProvider;
        private readonly TelemetryClient telemetryClient;
        private readonly ILogonActivity logonActivity;
        private readonly IHyperFindLoadAllActivity hyperFindLoadAllActivity;
        private readonly ShiftsTeamKronosDepartmentViewModel shiftsTeamKronosDepartmentViewModel;
        private readonly Utility utility;
        private readonly IGraphUtility graphUtility;
        private readonly AppSettings appSettings;
        private readonly IConfigurationProvider configurationProvider;
        private readonly IDistributedCache cache;
        private readonly IUserMappingProvider userMappingProvider;
        private readonly IHttpClientFactory httpClientFactory;

        /// <summary>
        /// Initializes a new instance of the <see cref="TeamDepartmentMappingController"/> class.
        /// </summary>
        /// <param name="teamDepartmentMappingProvider">configurationProvider DI.</param>
        /// <param name="telemetryClient">The logging mechanism through Application Insights.</param>
        /// <param name="logonActivity">Logon activity.</param>
        /// <param name="hyperFindLoadAllActivity">IHyperFindLoadAllActivity object.</param>
        /// <param name="shiftsTeamKronosDepartmentViewModel">ShiftsTeamKronosDepartmentViewModel object.</param>
        /// <param name="utility">Utility DI.</param>
        /// <param name="graphUtility">Having the ability to DI the mechanism to get the token from MS Graph.</param>
        /// <param name="appSettings">Configuration DI.</param>
        /// <param name="configurationProvider">ConfigurationProvider DI.</param>
        /// <param name="cache">Distributed cache.</param>
        /// <param name="userMappingProvider">User To User Mapping Provider.</param>
        /// <param name="httpClientFactory">httpClientFactory.</param>
        public TeamDepartmentMappingController(
            ITeamDepartmentMappingProvider teamDepartmentMappingProvider,
            TelemetryClient telemetryClient,
            ILogonActivity logonActivity,
            IHyperFindLoadAllActivity hyperFindLoadAllActivity,
            ShiftsTeamKronosDepartmentViewModel shiftsTeamKronosDepartmentViewModel,
            Utility utility,
            IGraphUtility graphUtility,
            AppSettings appSettings,
            IConfigurationProvider configurationProvider,
            IDistributedCache cache,
            IUserMappingProvider userMappingProvider,
            IHttpClientFactory httpClientFactory)
        {
            this.teamDepartmentMappingProvider = teamDepartmentMappingProvider;
            this.telemetryClient = telemetryClient;
            this.logonActivity = logonActivity;
            this.hyperFindLoadAllActivity = hyperFindLoadAllActivity;
            this.shiftsTeamKronosDepartmentViewModel = shiftsTeamKronosDepartmentViewModel;
            this.utility = utility;
            this.graphUtility = graphUtility;
            this.appSettings = appSettings;
            this.configurationProvider = configurationProvider;
            this.cache = cache;
            this.userMappingProvider = userMappingProvider;
            this.httpClientFactory = httpClientFactory;
        }

        /// <summary>
        /// Default action.
        /// </summary>
        /// <returns>Shifts team Kronos department mapping page.</returns>
        [HttpGet]
        public IActionResult Index()
        {
            this.telemetryClient.TrackTrace($"{MethodBase.GetCurrentMethod().Name}");

            this.ViewBag.IsUserLoggedIn = this.User.Identity.IsAuthenticated;
            this.ViewBag.EmailId = this.User.Identity.Name ?? string.Empty;

            return this.View();
        }

        /// <summary>
        /// Method to sync data for the first time.
        /// </summary>
        /// <returns>A type of <see cref="IActionResult"/>.</returns>
        public async Task<IActionResult> SyncDataFirstTimeAsync()
        {
            var client = this.httpClientFactory.CreateClient("ShiftsKronosIntegrationAPI");

            if (client.BaseAddress == null)
            {
                client.BaseAddress = new Uri(this.appSettings.BaseAddressFirstTimeSync);
            }

            client.Timeout = TimeSpan.FromMinutes(30);
            var checkSetUp = await client.GetAsync(new Uri(client.BaseAddress + "api/teams/CheckSetup")).ConfigureAwait(false);

            if (!checkSetUp.IsSuccessStatusCode)
            {
                return this.RedirectToAction("Index").WithErrorMessage(Resources.ErrorNotificationHeaderText, Resources.SetUpNotDoneMessage);
            }

            var graphConfigurationDetails = this.utility.GetTenantDetails();
            graphConfigurationDetails.ShiftsAdminAadObjectId = this.User.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
            graphConfigurationDetails.TenantId = this.User.GetTenantId();

            // Get JWT Token for API request
            TokenHelper tokenHelper = new TokenHelper(this.appSettings);
            string apiAccessToken = tokenHelper.GenerateToken();

            // Run sync Kronos to Shifts.
            using (var request = this.PrepareHttpRequest("api/SyncKronosToShifts/StartSync/false", apiAccessToken))
            {
                var syncKronosToShiftsResponse = await client.SendAsync(request).ConfigureAwait(false);

                if (!syncKronosToShiftsResponse.IsSuccessStatusCode)
                {
                    var syncKronosToShiftsError = await syncKronosToShiftsResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
                    this.telemetryClient.TrackTrace($"{MethodBase.GetCurrentMethod().Name} error: " + syncKronosToShiftsError);
                    return this.RedirectToAction("Index").WithErrorMessage(Resources.ErrorNotificationHeaderText, Resources.SyncKronosToShiftsError);
                }
            }

            return this.RedirectToAction("Index").WithSuccess(Resources.SuccessNotificationHeaderText, Resources.SetUpSuccessfulMessage);
        }

        /// <summary>
        /// The method will get the necessary configurations that have been saved.
        /// </summary>
        /// <returns>A list of the configurations.</returns>
        [HttpGet]
        public async Task<ActionResult> GetTeamDepartmentMappingAsync()
        {
            var mappedTeamsResult = await this.teamDepartmentMappingProvider.GetMappedTeamToDeptsWithJobPathsAsync().ConfigureAwait(false);
            var mappedTeamsResultViewModel = mappedTeamsResult.Select(
                m => new TeamsDepartmentMappingViewModel
                {
                    WorkforceIntegrationId = m.PartitionKey,
                    KronosOrgJobPath = Utility.OrgJobPathKronosConversion(m.RowKey),
                    KronosTimeZone = m.KronosTimeZone,
                    ShiftsTeamName = m.ShiftsTeamName,
                    TeamId = m.TeamId,
                    TeamsScheduleGroupId = m.TeamsScheduleGroupId,
                    TeamsScheduleGroupName = m.TeamsScheduleGroupName,
                }).ToList();
            return this.PartialView("_DataTable", mappedTeamsResultViewModel);
        }

        /// <summary>
        /// Navigation to the home page.
        /// </summary>
        /// <returns>A type of <see cref="IActionResult"/>.</returns>
        public IActionResult GoBack()
        {
            return this.RedirectToAction("Index", "UserMapping");
        }

        /// <summary>
        /// Method to Download template for UserToUserMapping.
        /// </summary>
        /// <returns>File to browser's response.</returns>
        public async Task<ActionResult> DownloadTemplateAsync()
        {
            using (MemoryStream memStream = await Helper.AzureStorageHelper.DownloadFileFromBlobAsync(
                     this.appSettings.StorageConnectionString,
                     this.appSettings.TemplatesContainerName,
                     this.appSettings.KronosShiftTeamDeptMappingTemplateName,
                     this.telemetryClient).ConfigureAwait(false))
            {
                return this.File(memStream.ToArray(), this.appSettings.ExcelContentType, this.appSettings.KronosShiftTeamDeptMappingTemplateName);
            }
        }

        /// <summary>
        /// Action method to Export data in Excel format.
        /// </summary>

Kronos-Shifts-Connector/Microsoft.Teams.Shifts.Integration/Microsoft.Teams.Shifts.Integration.Configuration/Views/TeamDepartmentMapping/Index.cshtml
@{
    ViewData["Title"] = "Team Department Mapping";
}

<link rel="stylesheet" href="~/css/spinner.css" type="text/css" />
<link rel="stylesheet" href="~/css/customizableStyle.css" type="text/css" />
<script src="../lib/jquery/jquery.min.js"></script>
<div id="messageHeader"></div>
<h3>Team and Department Mapping</h3>
<p style="margin-top: 20px;">
    @Resources.TeamDepartmentMappingPageInstructionText
    <ol>
        <li>@Resources.TeamDepartmentMappingPageInstructionTextStep1</li>
        <li>
            @Resources.TeamDepartmentMappingPageInstructionTextStep2
        <ul>
            <li>@Resources.TeamDepartmentMappingPageInstructionTextSubStep2</li>
        </ul>
    </li>
    <li>@Resources.TeamDepartmentMappingPageInstructionTextStep3</li>
</ol>
</p>

<div class="row contentMargin" style="margin-top: -80px; margin-left: 20px;">
    <div id="spinner" style="display: none">
        <partial name="~/Views/Shared/_Spinner.cshtml" />
    </div>

    <div class="form-group">
        <input type="button" id="exportBtnIdTeamsMapp" value="@Resources.ExportUserToUserMappingButtonText" class="btn btn-primary" onclick="location.href='@Url.Action("ExportToExcelAsync")'" />
        <input type="button" id="downloadTempIdTeamsMapp" value="@Resources.DownloadTemplateoUserMappingButtonText" class="btn btn-primary" onclick="location.href='@Url.Action("DownloadTemplateAsync")'" />
        <input type="button" id="importMappingIdTeamsMapp" value="@Resources.ImportUserToUserMappingButtonText" class="btn btn-primary" />
        <input type="file" id="fileControlImportTeamsMapp" name="file" style="display: none" onchange="fileSelectedEventTeamsMapp(this)" />

        <div class="respTxtTeamsToDeptMapping"></div>
        <div class="respTxtTeamsToDeptMappingSuccess"></div>
    </div>
    <br />
    <div id="teamDepartmentList"></div>
    <div class="btn-group" style="float: right;margin-top:20px;">
        <a asp-action="GoBack"><input type="button" value="@Resources.BackButtonText" class="btn btn-primary" /></a>
        <a asp-action="SyncDataFirstTimeAsync"><input type="button" value="@Resources.DoneButtonText" class="btn btn-success" /></a>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        //calling method to load or refresh the grid
        loadOrRefreshGridTeamAndDeptMapp();

        //Event to trigger the file upload control on clicking of the drop area
        $('#importMappingIdTeamsMapp').click(function () {
            $('#fileControlImportTeamsMapp').trigger('click');
        });
    });

    //function to load/refresh the grid showing user to user mapping
    function loadOrRefreshGridTeamAndDeptMapp() {
         $.ajax({
            type: "GET",
            url: '@Url.Action("GetTeamDepartmentMappingAsync")',
            success: function (result) {
                if (result != "") {
                    $("#teamDepartmentList").html(result);
                }
            }
        });

    }

    // Show spinner indicator on all AJAX calls
    $(document).ajaxSend(function () {
        $("#spinner").show();
    });

    // Hide spinner indicator when all AJAX calls stops
    $(document).ajaxStop(function () {
        $("#spinner").hide();
    });

    //function to handle file selection for Import Mapping
        function fileSelectedEventTeamsMapp(evt) {
            $(".respTxtTeamsToDeptMapping").html("");
            $(".respTxtTeamsToDeptMappingSuccess").html("");

        var fileUpload = $("#fileControlImportTeamsMapp").get(0);
        var files = fileUpload.files;

        var fileName = files[0].name;
        var ext = fileName.substring(fileName.lastIndexOf('.') + 1).toLowerCase();
        var allowedExt = ["xlsx", "xls"];

            if (!(allowedExt.indexOf(ext) == -1)) {

                var fileSize = 0.00;
                fileSize = Math.round(files[0].size * 100 / 1048576) / 100;
                if (fileSize > 0) {
                    var formData = new FormData();
                    formData.append("files", files[0]);
                    $.ajax({
                        type: "POST",
                        cache: false,
                        url: '@Url.Action("ImportMappingAsync")',
                        data: formData,
                        contentType: false,
                        processData: false,
                        dataType: "json",
                        success: function (jsonResponse) {
                            console.log(jsonResponse)
                            if (jsonResponse.isWorkforceIntegrationPresent) {
                                if (jsonResponse.response) {
                                    
                                    $(".respTxtTeamsToDeptMapping").html("");
                                    var htmlDiv = ' <div class="alert alert-success alert-dismissible" role="alert">' +
                                        '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>' +
                                        "Imported Successfully" +
                                        '</div>'
                                    setTimeout(function () {
                                        $("#messageHeader").html(htmlDiv);
                                    })
                                    setTimeout(function () {
                                        $("#messageHeader").html("");
                                    }, 3000);
                                    loadOrRefreshGridTeamAndDeptMapp();
                                }
                                else {
                                    $(".respTxtTeamsToDeptMappingSuccess").html("");
                                    var htmlDiv = ' <div class="alert alert-danger alert-dismissible" role="alert">' +
                                        '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>' +
                                        "The File's data is inconsistent" +
                                        '</div>'
                                    setTimeout(function () {
                                        $("#messageHeader").html(htmlDiv);
                                    })
                                    setTimeout(function () {
                                        $("#messageHeader").html("");
                                    }, 3000);
                                }
                            }
                            else {
                                $(".respTxtTeamsToDeptMapping").html(jsonResponse.error);
                            }
                            $("#fileControlImportTeamsMapp").prop("value", "");
                        },
                        error: function (jqXHR, exception) {
                            console.log(jsonResponse)
                            var htmlDiv = ' <div class="alert alert-danger alert-dismissible" role="alert">' +
                                '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>' +
                                "Some error occured." +
                                '</div>'
                            setTimeout(function () {
                                $("#messageHeader").html(htmlDiv);
                            })
                            setTimeout(function () {
                                $("#messageHeader").html("");
                            }, 3000);
                            setTimeout(function () {
                                $(".respTxtTeamsToDeptMapping").html("");
                            }, 3000);
                        }
                    });
                }
                else {
                    var htmlDiv = ' <div class="alert alert-danger alert-dismissible" role="alert">' +
                        '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>' +
                        "The file has no content." +
                        '</div>'
                    setTimeout(function () {
                        $("#messageHeader").html(htmlDiv);
                    })
                    setTimeout(function () {
                        $("#messageHeader").html("");
                    }, 3000);
                }
            }
            else {
                var htmlDiv = ' <div class="alert alert-danger alert-dismissible" role="alert">' +
                    '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>' +
                    "Type of file is not supported." +
                    '</div>'
                setTimeout(function () {
                    $("#messageHeader").html(htmlDiv);
                })
                setTimeout(function () {
                    $("#messageHeader").html("");
                }, 3000);
            }
    }

    function ajaxCallDeleteTeamDeptMapping(partitionKey, rowKey, element)
    {
      if (confirm("@Resources.TeamMappingDeletePopUpMessage")) {
        $.ajax({
              type: "POST",
              url: '@Url.Action("DeleteTeamsDeptMappingAsync")',
              dataType: "json",
              data: {
                  'partitionKey': partitionKey,
                  'rowKey': rowKey
              },
              success: function (jsonResponse) {
                  if (jsonResponse.response) {
                      $(element).closest('tr').remove();
                      var htmlDiv = ' <div class="alert alert-success alert-dismissible" role="alert">' +
                          '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>' +
                          "Deleted successfully." +
                          '</div>'
                      setTimeout(function () {
                          $("#messageHeader").html(htmlDiv);
                      })
                      setTimeout(function () {
                          $("#messageHeader").html("");
                      }, 3000);
                      $(".respTxtTeamsToDeptMapping").html("");
                      setTimeout(function () {
                          $(".respTxtTeamsToDeptMappingSuccess").html("");
                      }, 3000);
                      loadOrRefreshGridTeamAndDeptMapp();
                  }
                  else {
                      $(".respTxtTeamsToDeptMappingSuccess").html("");
                      setTimeout(function () {
                          $(".respTxtTeamsToDeptMapping").html("");
                      }, 3000);
                  }
              },
              error: function (jqXHR, exception) {
                  var htmlDiv = ' <div class="alert alert-danger alert-dismissible" role="alert">' +
                      '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>' +
                      "Some error occured." +
                      '</div>'
                  setTimeout(function () {
                      $("#messageHeader").html(htmlDiv);
                  })
                  setTimeout(function () {
                      $("#messageHeader").html("");
                  }, 3000);
              }
        });
    }
    }
</script>

Kronos-Shifts-Connector/Microsoft.Teams.Shifts.Integration/Microsoft.Teams.Shifts.Integration.Configuration/Views/TeamDepartmentMapping/_DataTable.cshtml
@model List<Microsoft.Teams.Shifts.Integration.Configuration.Models.TeamsDepartmentMappingViewModel>

<link href="../lib/datatables/css/jquery.dataTables.min.css" rel="stylesheet"/>
<script src="../lib/datatables/js/jquery.dataTables.min.js"></script>
<form asp-controller="TeamDepartmentMapping" asp-action="SaveShiftsTeamKronosDepartmentMappingAsync" method="post" class="formToSubmit">
    <table id="teamDeptMappTbl" class="table table-responsive" style="margin-top: 80px;">
        <thead>
            <tr>
                <th>Kronos Workforce Integration Id</th>
                <th>Kronos Org Job Path</th>
                <th>Kronos Time Zone</th>
                <th>Shifts Team Name</th>
                <th>Shifts Team Id</th>
                <th>Schedule Group Id</th>
                <th>Schedule Group Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count != 0)
            {
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.WorkforceIntegrationId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.KronosOrgJobPath)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.KronosTimeZone)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ShiftsTeamName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TeamId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TeamsScheduleGroupId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TeamsScheduleGroupName)
                        </td>
                        <td>
                            <input type="button" value="Delete" class="btn btn-primary deleteBtnUserMapp" onclick="ajaxCallDeleteTeamDeptMapping('@item.WorkforceIntegrationId', '@item.KronosOrgJobPath', this)" />
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td style="text-align:center;" colspan="6">
                        No Records found
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        $("#teamDeptMappTbl").dataTable({
            "columnDefs": [{
                "defaultContent": "-",
                "targets": "_all"
            }]
        });
    });
</script>

Kronos-Shifts-Connector/Microsoft.Teams.Shifts.Integration/Microsoft.Teams.Shifts.Integration.Configuration/Views/TeamDepartmentMapping/_KronosDepartment.cshtml
@model Microsoft.Teams.Shifts.Integration.Configuration.Models.ShiftsTeamKronosDepartmentViewModel

<div class="form-group" data-form-name="team">
    <div class="col-lg-3">
        @Html.LabelFor(model => model.KronosDepartmentName, htmlAttributes: new { @class = "font-bold" })
        <span class="mandatoryField">*</span>
    </div>
    <div class="col-lg-6">
        <select name="KronosDepartmentName" multiple size="4" class="form-control" asp-items="Model.KronosDepartments">
            <optgroup label="Select one department from Kronos to map">
            </optgroup>
        </select>
    </div>
    <div class="col-lg-offset-3 col-lg-5">
        <div id="teamStorageStatusMessage" class="error-message"></div>
    </div>
</div>
<div class="col-lg-12 marginBetweenView"/>
<div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary toggleToEditButton" id="btnSave" />
        <input type="button" value="@Resources.ImportTeamToDepartmentMappingButtonText" class="btn btn-primary"/>
</div>

Kronos-Shifts-Connector/Microsoft.Teams.Shifts.Integration/Microsoft.Teams.Shifts.Integration.Configuration/Views/TeamDepartmentMapping/_ShiftsTeam.cshtml
@model Microsoft.Teams.Shifts.Integration.Configuration.Models.ShiftsTeamKronosDepartmentViewModel

<form asp-controller="TeamDepartmentMapping" asp-action="SaveShiftsTeamKronosDepartmentMappingAsync" method="post" class="formToSubmit" style="margin-top:200px;">
    <div class="row">
        <div class="form-group" data-form-name="team">
            <div class="col-lg-3">
                @Html.LabelFor(model => model.ShiftsTeamName, htmlAttributes: new { @class = "font-bold" })
                <span class="mandatoryField">*</span>
            </div>
            <div class="col-lg-6">
                <select name="ShiftsTeamName" multiple size="4" class="form-control" asp-items="Model.ShiftTeams">
                    <optgroup label="Select Shifts Team">
                    </optgroup>
                </select>
            </div>
            <div class="col-lg-offset-3 col-lg-5">
                <div id="teamStorageStatusMessage" class="error-message"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <partial name="~/Views/TeamDepartmentMapping/_KronosDepartment.cshtml" />
    </div>
</form>